import Head from "next/head";
import { Formik, Form } from "formik";

import FormInput from "../components/Atoms/FormInput";
import styles from "../styles/Home.module.css";

const DisplaySection = () => {
  return (
    <Form>
      <FormInput id="xx" name="xx" label="XX" />
    </Form>
  );
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Form Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Formik
          initialValues={{}}
          onSubmit={() => {}}
          component={DisplaySection}
        />
      </main>
    </div>
  );
}
