#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Building your project before pushing'

npm run build ||
(
    echo '❌👷🔨❌ Better call Tri... Because your build failed ❌👷🔨❌
            Next export failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'
